### ISSUE TITLE
Executing the code and integrating with rasa chatbot

### ISSUE THREAD

**Issue by amruth-jaligama** [Meeting-Scheduler-Chatbot/website#1]
Hello, 

My name is Amruth and I am pursuing Masters In Data Science at the University Of North Texas. I am working on this project and I am not sure on how to execute the code whenever I run the docker-compose -f docker-compose.dev.yml up it gives me an error stating the .env file is missing. May I know how to create one and what all have to be there in the .env file and how to integrate the rasa-chatbot with it. I have gone through the deployment report but I am not able to understand on how to execute the code. Can you help me with it.

**Comment by cavitcakir** [comment]
Hello,

You should create a .env file under server folder. Afterward, add the following lines with respect to your own keys and passwords.

MONGO_DB=[database_name]
MONGO_USER=anywhere
MONGO_PASSWORD=[password]
DEBUG=0
PORT=8080
TOP_SECRET=[password]
FORCE_COLOR=1
CLIENT_ID=[Google Account id]
CLIENT_ID_PREV=[demo Google Cloud Account]
CLIENT_SECRET=[Google Cloud Account Secret]
CALENDAR_REDIRECT_URI=http://localhost:8080/api/google/callback
BOT_SECRET_PASS=[password]

@amruth-jaligama
